resolver: lts-14.11

# paths to local packages
packages:
  - hercules-ci-api
  - hercules-ci-api-core
  - hercules-ci-api-agent
  - hercules-ci-agent
  - tests/agent-test
extra-deps:
  - hnix-store-core-0.1.0.0@sha256:719a261870367b3ce2e2e8d11502e7170faa664109a14486b95b555bc3672807
  - nix-derivation-1.0.2@sha256:dc1f13f89d37d4dcc7a46dbac7f6b4e8cd2877f4af99e35b9cb8255d08179bd4
  - git: https://github.com/cachix/cachix
    commit: ba89b84c4de1acac8db86023ddf888a54c204fa8
    subdirs:
      - cachix
      - cachix-api
  - inline-c-0.9.0.0
  - inline-c-cpp-0.4.0.1

install-ghc: false  # we're using nixpkgs' ghc
system-ghc: true    # nixpkgs ghc is perceived as 'system ghc'

nix:
  packages: []      # use shell instead
  shell-file: ./nix/stack-shell.nix
  pure: false
